version: '3.8'
services:
  ideanest_backend:
    container_name: ideanest_backend
    build:
      context: .
      target: production
    environment:
      - NODE_ENV="production"
    ports:
      - '8080:3000'
    env_file:
      - ./.env
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-db:/data/mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

  redis:
    image: redis
    container_name: redis
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASS"
    env_file:
      - ./.env
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  mongo-db:
  redis:
    driver: local
